name: Deploy docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - run: npm ci

      - run: npm run build

      - name: Deploy Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm install
          build_command: npm run build
          path: ./packages/docs/storybook-static
          checkout: false